# Generated by Django 3.1.6 on 2021-06-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HallDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='null', max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('cost', models.CharField(max_length=10)),
                ('area', models.CharField(max_length=50)),
                ('hallimg', models.FileField(default='null', upload_to='media/hall_image')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(max_length=20)),
                ('list', models.CharField(default='null', max_length=20)),
            ],
        ),
    ]
