# Generated by Django 3.1.6 on 2021-06-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_auto_20210605_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='listm',
            field=models.ManyToManyField(blank=True, to='sites.HallDetail'),
        ),
    ]
