# Generated by Django 3.1.6 on 2021-06-06 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_userprofile_listm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='listm',
            new_name='lists',
        ),
    ]
